### PR TITLE
Created Rotating Windmill

### PR DESCRIPTION
**Pull request by kumarmanish03**
#69 
created windmill
https://codepen.io/manish-kumar-2000/pen/JjogbBV?editors=1100

### CODE REVIEW

**Comment by manish-kumar-2000** [comment]
[https://codepen.io/manish-kumar-2000/pen/JjogbBV?editors=1100](url)
Click this link

**Comment by manish-kumar-2000** [comment]
copy above link and open in new tab then this link open

**Comment by kumarmanish03** [comment]
@abhiandthetruth sir, points for this is not reflected in leaderboard

**Comment by abhishekmsingh** [comment]
looking into it

**Comment by abhishekmsingh** [comment]
updated

**Pull request merged**
