### PR TITLE
Animated Windmill

### PR DESCRIPTION
**Pull request by pradhuman1**
__69__
#69 
Screenshot 2020-01-25 at 3 35 42 PM

### CODE REVIEW

**Comment by pradhuman1** [comment]
Sir I didn't get point for SNOWMAN#86

**Comment by thesmallstar** [comment]
Correct issue number.

**Comment by pradhuman1** [comment]
Issue number is correct in both PR

**Comment by pradhuman1** [comment]
Sir please Review my PR#86(SNOWMAN) ISSUE#70 i didn't get points

**Comment by thesmallstar** [comment]
@abhiandthetruth

**Comment by abhishekmsingh** [comment]
@pradhuman1 marks updated for Pr #86. Merging this one

**Comment by pradhuman1** [comment]
@abhiandthetruth i get 20 points instead of 30 points

**Pull request merged**
