### PR TITLE
Pepe the frog

### PR DESCRIPTION
**Pull request by PratyushPareek**
__3__
created my folder
created artworks.md
added link to frog

### CODE REVIEW

**Comment by PratyushPareek** [comment]
Screenshot of Pepe:
pepe

**Comment by thesmallstar** [comment]
Which PR? xD

**Comment by PratyushPareek** [comment]
@thesmallstar  The ones in Monty-Python :/

Btw I think I only got 40 points for completing both tasks (frog and hero)
I had 10 points from before (adding my name in participants list) and now I have 50 points 
Please look into this 
Thanks!

**Comment by thesmallstar** [comment]
Put it on slack, leaderboard issues. It will be solved😁

**Comment by PratyushPareek** [comment]
Done

**Pull request merged**
