### PR TITLE
iPod classic and heroes/villains symbol done

### PR DESCRIPTION
**Pull request by ananya-mohanty**
__1__

Task 1 done

### CODE REVIEW

**Comment by ananya-mohanty** [comment]
__4__

Task 3 done

**Comment by ekanban** [comment]
Comment the screenshot

**Comment by ananya-mohanty** [comment]
Screenshot 2020-01-20 at 11 43 07 PM
Screenshot 2020-01-20 at 11 43 18 PM

**Comment by zerefwayne** [comment]
@ananya-mohanty Please send separate pull requests for the tasks and don't forget to mention the issue number in the format __34__ on each PR.

**Pull request closed without merging**
