### PR TITLE
Completed Task-4(animated windmill)

### PR DESCRIPTION
**Pull request by aarpit1010**
__69__
#69 

Created a rotating windmill using animation in CSS.

### CODE REVIEW

**Comment by aarpit1010** [comment]
https://codepen.io/aarpit1010/pen/LYEaOZQ

**Comment by thesmallstar** [comment]
conflicts.

**Comment by aarpit1010** [comment]
@thesmallstar  sir, merge conflicts are resolved. Pls. Review PR#95

**Comment by aarpit1010** [comment]
@zerefwayne  Sir, pls review PR#95.

**Comment by aarpit1010** [comment]
@thesmallstar sir pls accept my PR#95

**Pull request merged**
