### PR TITLE
Task 4

### PR DESCRIPTION
**Pull request by starboi02**
__69__

Created Windmill

Windmill

### CODE REVIEW

**Comment by thesmallstar** [comment]
Add animation

**Comment by starboi02** [comment]
@thesmallstar Added animation

**Comment by starboi02** [comment]
https://codepen.io/starboi02/pen/mdyoeEa

**Comment by thesmallstar** [comment]
I don't see any

**Comment by starboi02** [comment]
@thesmallstar Sorry sir I stoped the rotation than to take screenshot,now its working

**Comment by starboi02** [comment]
@thesmallstar Please review

**Comment by starboi02** [comment]
@thesmallstar please review

**Comment by starboi02** [comment]
@thesmallstar please review

**Comment by starboi02** [comment]
@zerefwayne please review

**Comment by starboi02** [comment]
@zerefwayne please review

**Comment by thesmallstar** [comment]
nice :D

**Pull request merged**
